server:
  port: ${PORT:8080}

spring:
  application:
    name: banking
  datasource:
    url: jdbc:sqlite:/data/banking.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true
  packages-to-scan: com.api.banking.controller
